#!/bin/bash -e
# Wrapper to deal with newer Ubuntu versions that don't have py2 installed
# by default; when series-upgrading, ensure that the python3 packages are
# installed.

declare -a DEPS=('apt' 'netaddr' 'netifaces' 'pip' 'yaml')

check_and_install() {
    pkg="${1}-${2}"
    if ! dpkg -s ${pkg} 2>&1 > /dev/null; then
        apt-get -y install ${pkg}
    fi
}

PYTHON="python3"

for dep in ${DEPS[@]}; do
    check_and_install ${PYTHON} ${dep}
done

exec ./hooks/upgrade-charm.real
